# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "sow-what"
author = "Susan Collins"
release = "0.1.0"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration


# fmt: off
extensions = [
	"sphinx.ext.autodoc",
	"sphinx.ext.intersphinx",     # enables linking of docs & Python ojects across Sphinx repositories
	"sphinx.ext.mathjax",         # enables formatting of LaTeX math in `.. math::` directives
	"sphinx.ext.viewcode",        # link from docstrings directly to code declarations
	"numpydoc",                   # format Numpy-style docstrings as reST
	"sphinx_copybutton",          # copy entire blocks of code from `.. code::` directives, omitting prompts
	"sphinx_design",              # include nice visual styling
	"sphinx_last_updated_by_git", # set last-updated date of pages to last change in Git, as opposed to doc build
	"sphinx_new_tab_link",        # open external links in new tabs
]
# fmt: on

# -- numpydoc extension ------------------------------------------------------

numpydoc_class_members_toctree = False
numpydoc_xref_param_type = True


# -- autodoc extension -------------------------------------------------------

# for classes, show docstrings for class and class.__init__()
autoclass_content = "both"

# fmt: off
autodoc_default_options = {

	# group special methods & non-special methods, rather than alphabetical
	"member-order": "groupwise",

	# show inheritance, when methods are inherited
	"show-inheritance": True,

	# show signatures of methods without docstrings
	"undoc-members": True,

	# by default, don't document __dunder_methods__
	"special-members": False,

	# document private methods
	"private-members": True,

	# document inherited methods
	"inherited-members": False,
}
# fmt: on

# Add any paths that contain Jinja templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of strings
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"
modindex_common_prefix = ["sow_what."]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_book_theme"
html_last_updated_fmt = "%b %d, %Y"
html_copy_source = True
html_show_sourcelink = True


# Theme options, see https://sphinx-book-theme.readthedocs.io/en/stable/reference.html
html_theme_options = {
    "path_to_docs": "doc/source/",
    "repository_url": "https://github.com/concentricbyginkgo/sow-what",
    "use_source_button": True,
    "use_repository_button": True,
    "use_issues_button": True,
    "use_fullscreen_button": False,
}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# Output file base name for HTML help builder.
htmlhelp_basename = "sow-what-doc"
